# Generated by Django 4.2.5 on 2023-09-25 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ("-check_in_date",)},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("room_type",)},
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={"ordering": ("capacity",)},
        ),
    ]
